{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_file_005.Test_Credence_005 object at 0x000001A0E6B57D50>\n\n>   ???\nE   assert False\n\nD:\\Credence Class Notes\\CredenceBatches\\CredenceBatch#14 & 15\\Pytest_July\\test_file_005.py:11: AssertionError"}, "attachments": [{"name": "stdout", "source": "0b12e1c4-2cad-4db7-86fc-3e27c8be8157-attachment.txt", "type": "text/plain"}], "start": 1690695016345, "stop": 1690695016345, "uuid": "a256cd52-3dc7-4c0a-b70a-5b76328f9c2c", "historyId": "3373f973f87d181b033c1208fbde30ae", "testCaseId": "3373f973f87d181b033c1208fbde30ae", "fullName": "test_file_005.Test_Credence_005#test_mul_004", "labels": [{"name": "suite", "value": "test_file_005"}, {"name": "subSuite", "value": "Test_Credence_005"}, {"name": "host", "value": "DESKTOP-S60SV8I"}, {"name": "thread", "value": "7456-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_file_005"}]}